const locations = [
  { id: 1, name: "City" },
  { id: 2, name: "Berlin" },
  { id: 3, name: "Ottawa" },
  { id: 4, name: "Canberra" },
  { id: 5, name: "Kyiv" },
  { id: 6, name: "Paris" },
  { id: 7, name: "Rome" },
];
const types = [
  { id: 1, name: "House" },
  { id: 2, name: "Apartment" },
  { id: 3, name: "Hotel" },
  { id: 4, name: "Villa" },
];

const residents = [
  {
    id: 1,
    img: "/../public/images/1.png",
    name: "Duncans Mills",
    location: "California, USA",
    rating: 4.9,
    price: 260,
    type: "Resident",
    rooms: 3,
    lat: 38.45,
    long: -123.059,
  },
  {
    id: 2,
    img: "/../public/images/2.png",
    name: "Villa Dago",
    location: "Walnar, Denmark",
    rating: 5.0,
    price: 380,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 3,
    img: "/../public/images/3.png",
    name: "Jungle Paradise",
    location: "Cikarang, Indonesia",
    rating: 4.3,
    price: 400,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 4,
    img: "/../public/images/4.png",
    name: "Surya Kencana",
    location: "Rome, Italy",
    rating: 4.9,
    price: 200,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 5,
    img: "/../public/images/5.png",
    name: "Tlewa bormeso",
    location: "Sevilla, Spain",
    rating: 4.4,
    price: 280,
    type: "Resident",
    rooms: 2,
    lat: 1,
    long: 1,
  },
  {
    id: 6,
    img: "/../public/images/6.png",
    name: "Hinter dem Alltag",
    location: "Hamburg, Germany",
    rating: 4.6,
    price: 430,
    type: "Resident",
    rooms: 3,
    lat: 38.453802,
    long: -123.065301,
  },
];

const reviews = [
  {
    id: 1,
    img: "/../public/images/person1.png",
    name: "Jane Cooper",
    work: "Marketing Coordinator",
    text: "I can't thank SogeKing Real Estate Company enough for their outstanding service. From the moment I started working with them, their team of dedicated professionals went above and beyond to help me find my dream home.",
  },
  {
    id: 2,
    img: "/../public/images/person2.png",
    name: "Cameron Williamson",
    work: "Web Designer",
    text: "Choosing SogeKing Real Estate Company was the best decision I made for my home-buying journey. Their team of knowledgeable agents provided invaluable guidance and support throughout the entire process.",
  },
  {
    id: 3,
    img: "/../public/images/person3.png",
    name: "Darrell Steward",
    work: "President of Sales",
    text: "“I had an exceptional experience with SogeKing Real Estate Company. Their team of experts was highly professional and went the extra mile to assist me in finding the perfect property. They provided comprehensive market insights.”",
  },
  {
    id: 4,
    img: "/../public/images/person4.png",
    name: "Eleanor Pena",
    work: "Medical Assistant",
    text: "I am incredibly grateful to SogeKing Real Estate Company for their outstanding service. Their team of friendly and knowledgeable agents made the process of selling my home stress-free and efficient.",
  },
];

export { locations, types, residents, reviews };
