const locations = [
  { id: 1, name: "City" },
  { id: 2, name: "Berlin" },
  { id: 3, name: "Ottawa" },
  { id: 4, name: "Canberra" },
  { id: 5, name: "Kyiv" },
  { id: 6, name: "Paris" },
  { id: 7, name: "Rome" },
];
const types = [
  { id: 1, name: "House" },
  { id: 2, name: "Apartment" },
  { id: 3, name: "Hotel" },
  { id: 4, name: "Villa" },
];

const residents = [
  {
    id: 1,
    img: "/../public/images/1.png",
    name: "Duncans Mills",
    location: "California, USA",
    rating: 4.9,
    price: 760,
    type: "Resident",
    rooms: 3,
    lat: 38.45,
    long: -123.059,
  },
  {
    id: 2,
    img: "/../public/images/2.png",
    name: "Villa Dago",
    location: "Walnar, Denmark",
    rating: 5.0,
    price: 380,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 3,
    img: "/../public/images/3.png",
    name: "Jungle Paradise",
    location: "Cikarang, Indonesia",
    rating: 4.3,
    price: 400,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 4,
    img: "/../public/images/4.png",
    name: "Surya Kencana",
    location: "Rome, Italy",
    rating: 4.9,
    price: 330,
    type: "Resident",
    rooms: 1,
    lat: 33,
    long: 13,
  },
  {
    id: 5,
    img: "/../public/images/5.png",
    name: "Tlewa bormeso",
    location: "Sevilla, Spain",
    rating: 4.4,
    price: 480,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 6,
    img: "/../public/images/6.png",
    name: "Penthouse with Schwimmbad",
    location: "California, USA",
    rating: 4.6,
    price: 220,
    type: "Resident",
    rooms: 4,
    lat: 38.2,
    long: -123.065301,
  },
  {
    id: 7,
    img: "/../public/images/1.png",
    name: "Duncans Mills",
    location: "California, USA",
    rating: 4.9,
    price: 760,
    type: "Resident",
    rooms: 2,
    lat: 38.45,
    long: -123.059,
  },
  {
    id: 8,
    img: "/../public/images/2.png",
    name: "Villa Dago",
    location: "Walnar, Denmark",
    rating: 5.0,
    price: 380,
    type: "Resident",
    rooms: 1,
    lat: 1,
    long: 1,
  },
  {
    id: 9,
    img: "/../public/images/3.png",
    name: "Jungle Paradise",
    location: "Cikarang, Indonesia",
    rating: 4.3,
    price: 400,
    type: "Resident",
    rooms: 3,
    lat: 1,
    long: 1,
  },
  {
    id: 10,
    img: "/../public/images/4.png",
    name: "Surya Kencana",
    location: "Rome, Italy",
    rating: 4.9,
    price: 330,
    type: "Resident",
    rooms: 3,
    lat: 52.520078,
    long: 13.404902,
  },
  {
    id: 11,
    img: "/../public/images/5.png",
    name: "Tlewa bormeso",
    location: "Sevilla, Spain",
    rating: 4.4,
    price: 480,
    type: "Resident",
    rooms: 2,
    lat: 52.520078,
    long: 13.404902,
  },
  {
    id: 12,
    img: "/../public/images/6.png",
    name: "Hinter dem Alltag",
    location: "Berlin, Germany",
    rating: 4.6,
    price: 220,
    type: "Resident",
    rooms: 3,
    lat: 52.520078,
    long: 13.404902,
  },
  {
    id: 13,
    img: "/../public/images/13.jpg",
    name: "Cozy Apartment in the City",
    location: "Berlin, Germany",
    rating: 4.5,
    price: 2300,
    rooms: 3,
    lat: 52.52,
    long: 13.405,
  },
  {
    id: 14,
    img: "/../public/images/14.png",
    name: "Modern Loft with a View",
    location: "New York City, USA",
    rating: 4.8,
    price: 1200,
    rooms: 4,
    lat: 40.7128,
    long: -74.006,
  },
  {
    id: 15,
    img: "/../public/images/15.png",
    name: "Sunny Beachfront Villa",
    location: "Barcelona, Spain",
    rating: 4.7,
    price: 530,
    rooms: 5,
    lat: 41.3851,
    long: 2.1734,
  },
  {
    id: 16,
    name: "Charming Cottage in the Countryside",
    location: "Cotswolds, United Kingdom",
    rating: 4.9,
    price: 230,
    rooms: 2,
    lat: 51.878,
    long: -2.2387,
  },
  {
    id: 17,
    img: "/../public/images/17.jpg",
    name: "Luxury Penthouse in the Heart of Paris",
    location: "Paris, France",
    rating: 4.6,
    price: 320,
    rooms: 6,
    lat: 48.8566,
    long: 2.3522,
  },
  {
    id: 18,
    name: "Seaside Retreat in Maldives",
    location: "Maldives",
    rating: 4.7,
    price: 740,
    rooms: 4,
    lat: 3.2028,
    long: 73.2207,
  },
  {
    id: 19,
    name: "Rustic Cabin in the Rocky Mountains",
    location: "Colorado, USA",
    rating: 4.4,
    price: 800,
    rooms: 2,
    lat: 39.5501,
    long: -105.7821,
  },
  {
    id: 20,
    img: "/../public/images/20.png",
    name: "Rustic Cabin in the Rocky Mountains",
    location: "Colorado, USA",
    rating: 4.4,
    price: 800,
    rooms: 2,
    lat: 39.5501,
    long: -105.7821,
  },
  {
    id: 21,
    img: "/../public/images/21.png",
    name: "Seaview Apartment in Santorini",
    location: "Santorini, Greece",
    rating: 4.7,
    price: 2800,
    rooms: 3,
    lat: 36.3932,
    long: 25.4615,
  },
  {
    id: 22,
    img: "/../public/images/22.png",
    name: "Mountain Retreat in Switzerland",
    location: "Zermatt, Switzerland",
    rating: 4.9,
    price: 4200,
    rooms: 6,
    lat: 46.0207,
    long: 7.7491,
  },
  {
    id: 23,
    img: "/../public/images/23.png",
    name: "Cosy Cabin in the Woods",
    location: "Vancouver, Canada",
    rating: 4.6,
    price: 1500,
    rooms: 2,
    lat: 49.2827,
    long: -123.1207,
  },
  {
    id: 24,
    img: "/../public/images/24.png",
    name: "Skyline Apartment in Chicago",
    location: "Chicago, USA",
    rating: 4.5,
    price: 1900,
    rooms: 3,
    lat: 41.8781,
    long: -87.6298,
  },
  {
    id: 25,
    img: "/../public/images/25.png",
    name: "Chic Loft in Barcelona",
    location: "Barcelona, Spain",
    rating: 4.8,
    price: 3200,
    rooms: 4,
    lat: 41.3851,
    long: 2.1734,
  },
  {
    id: 26,
    img: "/../public/images/26.png",
    name: "Riverside Retreat in Vienna",
    location: "Vienna, Austria",
    rating: 4.4,
    price: 2000,
    rooms: 3,
    lat: 48.2082,
    long: 16.3738,
  },
  {
    id: 27,
    img: "/../public/images/27.png",
    name: "Mountain View Chalet in Switzerland",
    location: "Zurich, Switzerland",
    rating: 4.7,
    price: 3000,
    rooms: 4,
    lat: 47.3769,
    long: 8.5417,
  },
  {
    id: 28,
    img: "/../public/images/28.png",
    name: "Serenity Villa in Bali",
    location: "Bali, Indonesia",
    rating: 4.9,
    price: 2200,
    rooms: 5,
    lat: -8.3405,
    long: 115.092,
  },
  {
    id: 29,
    img: "/../public/images/29.png",
    name: "Stylish Loft in Amsterdam",
    location: "Amsterdam, Netherlands",
    rating: 4.6,
    price: 2700,
    rooms: 3,
    lat: 52.3676,
    long: 4.9041,
  },
  {
    id: 30,
    img: "/../public/images/30.png",
    name: "Seaside Villa in Malibu",
    location: "Malibu, USA",
    rating: 4.5,
    price: 3800,
    rooms: 6,
    lat: 34.0259,
    long: -118.7798,
  },
  {
    id: 31,
    img: "/../public/images/31.png",
    name: "Historic Apartment in Rome",
    location: "Rome, Italy",
    rating: 4.7,
    price: 1900,
    rooms: 2,
    lat: 41.9028,
    long: 12.4964,
  },
  {
    id: 32,
    img: "/../public/images/32.png",
    name: "Penthouse Suite in Dubai",
    location: "Dubai, UAE",
    rating: 4.8,
    price: 4500,
    rooms: 5,
    lat: 25.2048,
    long: 55.2708,
  },
  {
    id: 33,
    img: "/../public/images/33.png",
    name: "Lakefront Cabin in Canada",
    location: "Ontario, Canada",
    rating: 4.6,
    price: 1700,
    rooms: 3,
    lat: 45.4215,
    long: -75.6972,
  },
  {
    id: 34,
    img: "/../public/images/34.png",
    name: "Elegant Townhouse in London",
    location: "London, United Kingdom",
    rating: 4.9,
    price: 2800,
    rooms: 4,
    lat: 51.5074,
    long: -0.1278,
  },
  {
    id: 35,
    img: "/../public/images/35.png",
    name: "Beachfront Bungalow in Hawaii",
    location: "Hawaii, USA",
    rating: 4.5,
    price: 3600,
    rooms: 3,
    lat: 21.3069,
    long: -157.8583,
  },
  {
    id: 36,
    img: "/../public/images/36.png",
    name: "Countryside Cottage in Ireland",
    location: "Dublin, Ireland",
    rating: 4.7,
    price: 2000,
    rooms: 2,
    lat: 53.3498,
    long: -6.2603,
  },
  {
    id: 37,
    img: "/../public/images/37.png",
    name: "City Center Studio in Prague",
    location: "Prague, Czech Republic",
    rating: 4.4,
    price: 1500,
    rooms: 1,
    lat: 50.0755,
    long: 14.4378,
  },
  {
    id: 38,
    img: "/../public/images/38.png",
    name: "Mansion House in New Orleans",
    location: "New Orleans, USA",
    rating: 4.8,
    price: 3200,
    rooms: 5,
    lat: 29.9511,
    long: -90.0715,
  },
  {
    id: 0,
    img: "/../public/images/39.png",
    name: "Historic Villa in Florence",
    location: "Florence, Italy",
    rating: 4.6,
    price: 2300,
    rooms: 4,
    lat: 43.7696,
    long: 11.2558,
  },
  {
    id: 39,
    img: "/../public/images/39.jpg",
    name: "Modern Apartment in Berlin Mitte",
    location: "Berlin, Germany",
    rating: 4.5,
    price: 1200,
    rooms: 3,
    lat: 52.52,
    long: 13.405,
  },
  {
    id: 40,
    img: "/../public/images/40.jpg",
    name: "Charming Studio near Alexanderplatz",
    location: "Berlin, Germany",
    rating: 4.8,
    price: 1500,
    rooms: 2,
    lat: 52.5219,
    long: 13.4132,
  },
  {
    id: 41,
    img: "/../public/images/41.jpg",
    name: "Spacious Loft in Kreuzberg",
    location: "Berlin, Germany",
    rating: 4.7,
    price: 1800,
    rooms: 4,
    lat: 52.5009,
    long: 13.4115,
  },
  {
    id: 42,
    img: "/../public/images/42.png",
    name: "Luxury Penthouse in Prenzlauer Berg",
    location: "Berlin, Germany",
    rating: 4.9,
    price: 2500,
    rooms: 5,
    lat: 52.5292,
    long: 13.4111,
  },
  {
    id: 43,
    img: "/../public/images/43.jpg",
    name: "Cozy Apartment in Friedrichshain",
    location: "Berlin, Germany",
    rating: 4.6,
    price: 1400,
    rooms: 2,
    lat: 52.5159,
    long: 13.4547,
  },
  {
    id: 44,
    img: "/../public/images/44.jpg",
    name: "Riverside Retreat in Treptow",
    location: "Berlin, Germany",
    rating: 4.4,
    price: 1900,
    rooms: 3,
    lat: 52.4809,
    long: 13.4557,
  },
  {
    id: 45,
    img: "/../public/images/7.png",
    name: "Modern Apartment near Tiergarten",
    location: "Berlin, Germany",
    rating: 4.7,
    price: 2100,
    rooms: 4,
    lat: 52.5143,
    long: 13.3506,
  },
  {
    id: 46,
    img: "/../public/images/8.png",
    name: "Chic Loft in Charlottenburg",
    location: "Berlin, Germany",
    rating: 4.8,
    price: 2300,
    rooms: 3,
    lat: 52.5167,
    long: 13.3047,
  },
  {
    id: 47,
    img: "/../public/images/9.png",
    name: "Sunny Apartment in Wedding",
    location: "Berlin, Germany",
    rating: 4.6,
    price: 1600,
    rooms: 2,
    lat: 52.5535,
    long: 13.3492,
  },
  {
    id: 48,
    img: "/../public/images/10.png",
    name: "City Center Studio in Mitte",
    location: "Berlin, Germany",
    rating: 4.5,
    price: 1800,
    rooms: 1,
    lat: 52.5204,
    long: 13.4073,
  },
  {
    id: 49,
    img: "/../public/images/11.png",
    name: "Charming Apartment in Moabit",
    location: "Berlin, Germany",
    rating: 4.7,
    price: 2000,
    rooms: 3,
    lat: 52.5258,
    long: 13.3365,
  },
  {
    id: 50,
    img: "/../public/images/12.png",
    name: "Rooftop Penthouse in Schöneberg",
    location: "Berlin, Germany",
    rating: 4.9,
    price: 2800,
    rooms: 4,
    lat: 52.4883,
    long: 13.3517,
  },
];

const reviews = [
  {
    id: 1,
    img: "/../public/images/person1.png",
    name: "Jane Cooper",
    work: "Marketing Coordinator",
    text: "I can't thank SogeKing Real Estate Company enough for their outstanding service. From the moment I started working with them, their team of dedicated professionals went above and beyond to help me find my dream home.",
  },
  {
    id: 2,
    img: "/../public/images/person2.png",
    name: "Cameron Williamson",
    work: "Web Designer",
    text: "Choosing SogeKing Real Estate Company was the best decision I made for my home-buying journey. Their team of knowledgeable agents provided invaluable guidance and support throughout the entire process.",
  },
  {
    id: 3,
    img: "/../public/images/person3.png",
    name: "Darrell Steward",
    work: "President of Sales",
    text: "“I had an exceptional experience with SogeKing Real Estate Company. Their team of experts was highly professional and went the extra mile to assist me in finding the perfect property. They provided comprehensive market insights.”",
  },
  {
    id: 4,
    img: "/../public/images/person4.png",
    name: "Eleanor Pena",
    work: "Medical Assistant",
    text: "I am incredibly grateful to SogeKing Real Estate Company for their outstanding service. Their team of friendly and knowledgeable agents made the process of selling my home stress-free and efficient.",
  },
];

export { locations, types, residents, reviews };
