import "./globals.css";
import { Inter } from "next/font/google";
import { StoreProvider } from "./redux/provider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
